PG_FUNCTION_INFO_V1(S2Cell_as_S2Point);
PG_FUNCTION_INFO_V1(S2Cell_as_S2LatLng);

PG_FUNCTION_INFO_V1(S2LatLng_as_S2Point);
PG_FUNCTION_INFO_V1(S2LatLng_as_S2Cell);

PG_FUNCTION_INFO_V1(S2Point_as_S2Cell);
PG_FUNCTION_INFO_V1(S2Point_as_S2LatLng);
